### ISSUE TITLE
Lima compilation option fails

### ISSUE THREAD

**Issue by mpoudot** [LIHPC-Computational-Geometry/gmds#369] opened 2024-03-14 08:11 UTC
`spack install gmds +lima` gives the following error :
` /tmp/oudotmp/spack-stage/spack-stage-gmds-1.2.1-rasrjyfcex6wsqa7ff7c3aq6msvgtts7/spack-src/pygmds/src/gmds_binding.cpp:2:10: fatal error: gmds/blocking/CurvedBlocking.h: No such file or directory`

It seems that lima option depends on blocking option
`spack install gmds +blocking +lima` works

**Comment by nicolaslg** [comment] 2024-04-03 21:04
It is actually the python bindings that require `blocking`, and since the `python` variant is True by default the installation encounters this problem.
I will close this issue and pursue in the newer issue #374

Duplicate of #374

**Closed by nicolaslg** 2024-04-03 21:04 UTC
